services:
  game-launcher-service:
    env_file:
      - game_launcher.env
    build:
      context: requirements/game_launcher
      args:
        REPO: game-launcher
        PROJECT: game_launcher
        PORT: 9999
        BRANCH: main
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    expose:
      - 9999
    ports:
      - "20000-20010:20000-20010"
    container_name: pong_launcher_service_cont

  game-launcher-nginx:
    depends_on:
      game-launcher-service:
        condition: service_healthy
    build: requirements/nginx
    ports:
      - "9999:9999"
    healthcheck:
      test: ["CMD-SHELL", "service nginx status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    container_name: pong_launcher_server_cont
