import Login from "/components/Login.js";
import Register from "/components/Register.js";
import Link from "/components/Link.js";
import Router from "/components/Router.js";
import Home from "/components/Home.js";
import NavBar from "/components/NavBar.js";
import Settings from "/components/Settings.js";
import Infos from "/components/Infos.js";
import ChooseGame from "/components/ChooseGame.js";
import OtpInput from "/components/OtpInput.js";
import CustomFriends from "./components/friends";
import Intra from "/components/Intra.js";
import LocalPongForm from "./components/LocalPongForm.js";
import LocalPongGame from "./components/LocalPongGame.js";
import PongMatchmaking from "./components/PongMatchmaking.js";
import RemotePongGame from "./components/RemotePongGame.js";
import LocalGunFightForm from "./components/LocalGunFightForm";
import LocalGunFightGame from "./components/LocalGunFightGame";
import RemoteGunFightGame from "./components/RemoteGunFightGame";
import CustomPongSelector from "./components/PongModeSelector";
import CustomTournamentPong from "./components/PongTournament";
import CustomGunFightSelector from "./components/GunFightSelector";
import Stats from "./components/Stats.js";
import EndGame from "./components/EndGame";
import GunfightMatchmaking from "./components/GunfightMatchmaking";
import CustomTournamentGunfight from "./components/GunfightTournament";
import CustomErrorPage from "./components/error_404.js";
import PongCommands from "./components/PongCommands";
import GunfightCommands from "./components/GunfightCommands";


customElements.define("login-page", Login);
customElements.define("register-page", Register);
customElements.define("home-page", Home);
customElements.define("settings-page", Settings);
customElements.define("link-route", Link);
customElements.define("router-outlet", Router);
customElements.define("nav-bar", NavBar);
customElements.define("infos-page", Infos);
customElements.define("choose-page", ChooseGame);
customElements.define("otp-input", OtpInput);
customElements.define("stats-page", Stats);
customElements.define('intra-page', Intra);
customElements.define('local-pong-form', LocalPongForm);
customElements.define('local-pong-game', LocalPongGame);
customElements.define('pong-matchmaking', PongMatchmaking);
customElements.define('gunfight-matchmaking', GunfightMatchmaking);
customElements.define('remote-pong-game', RemotePongGame);
customElements.define('local-gunfight-form', LocalGunFightForm);
customElements.define('local-gunfight-game', LocalGunFightGame);
customElements.define('remote-gunfight-game', RemoteGunFightGame);
customElements.define('pong-selector', CustomPongSelector);
customElements.define('gunfight-selector', CustomGunFightSelector);
customElements.define("friends-page", CustomFriends);
customElements.define("local-pong-tournament", CustomTournamentPong);
customElements.define('end-game-modal', EndGame);
customElements.define("local-gunfight-tournament", CustomTournamentGunfight)
customElements.define("error-page", CustomErrorPage);
customElements.define("pong-commands", PongCommands);
customElements.define("gunfight-commands", GunfightCommands);
