# Generated by Django 5.0.4 on 2024-05-17 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('elo', models.IntegerField(default=1500)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='GunFightStats',
            fields=[
                ('stats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stats.stats')),
            ],
            bases=('stats.stats',),
        ),
        migrations.CreateModel(
            name='PongStats',
            fields=[
                ('stats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stats.stats')),
            ],
            bases=('stats.stats',),
        ),
        migrations.AddField(
            model_name='stats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.player'),
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameAddr', models.CharField(blank=True, max_length=21, null=True)),
                ('game', models.CharField(max_length=25)),
                ('elo', models.IntegerField()),
                ('tolerance', models.IntegerField(default=200)),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='stats.player')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stats.player')),
            ],
        ),
    ]
