# Generated by Django 5.0.4 on 2024-05-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_user_displayname'),
        ('login', '0010_user_login_42'),
    ]

    operations = [
    ]
