services:
  auth-postgres:
    hostname: postgres
    env_file:
      - auth.env
    image: postgres
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: auth_database_cont

  auth-service:
    image: auth_service
    depends_on:
      auth-postgres:
        condition: service_healthy
    env_file:
      - auth.env
    build:
      context: requirements/auth
      args:
        REPO: auth_service
        PROJECT: auth
        BRANCH: main
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        PORT: 4444
    expose:
      - 4444
    container_name: auth_service_cont

  auth-nginx:
    image: auth_server
    depends_on:
      auth-service:
        condition: service_healthy
    build: requirements/nginx
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD-SHELL", "service nginx status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    container_name: auth_server_cont
