# Generated by Django 5.0.4 on 2024-04-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_login_attempt_user_totp_enabled_user_totp_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_attempt',
            field=models.DateField(default=None, null=True),
        ),
    ]
