# Generated by Django 5.0.4 on 2024-04-30 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_user_displayname_remove_user_gunfightelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='displayName',
            field=models.CharField(max_length=25, null=True, validators=[django.core.validators.MinLengthValidator(5, 'Must contains at least 5 char')]),
        ),
    ]
