services:
  user-redis:
    hostname: redis
    env_file:
      - user.env
    image: redis
    expose:
      - 6379
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  user-postgres:
    hostname: postgres
    env_file:
      - user.env
    image: postgres
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: user_database_cont

  user-service:
    image: user_service
    depends_on:
      user-postgres:
        condition: service_healthy
    env_file:
      - user.env
    build:
      context: requirements/user
      args:
        REPO: user-service
        PROJECT: userService
        PORT: 4646
        BRANCH: main
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    expose:
      - 4646
    container_name: user_service_cont

  user-nginx:
    image: user_server
    depends_on:
      user-service:
        condition: service_healthy
    build: requirements/nginx
    ports:
      - "4646:4646"
    healthcheck:
      test: ["CMD-SHELL", "service nginx status"]
      interval: 12s
      timeout: 10s
      retries: 5
      start_period: 10s
    container_name: user_server_cont
