services:
  game-provider-service:
    env_file:
      - game_provider.env
    build:
      context: requirements/game_provider
      args:
        REPO: gameProvider
        PROJECT: gameProvider
        PORT: 5252
        BRANCH: main
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    expose:
      - 5252
  game-provider-nginx:
    depends_on:
      game-provider-service:
        condition: service_healthy
    build: requirements/nginx
    ports:
      - "5252:5252"
    healthcheck:
      test: ["CMD-SHELL", "service nginx status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
