# Generated by Django 5.0.4 on 2024-04-24 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=15, unique=True)),
                ('displayName', models.CharField(max_length=25, null=True, validators=[django.core.validators.MinLengthValidator(5, 'Must contains at least 5 char')])),
            ],
        ),
    ]
