# Generated by Django 5.0.4 on 2024-04-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('displayName', models.CharField(max_length=25)),
                ('pongElo', models.PositiveIntegerField(default=200)),
                ('gunFightElo', models.PositiveIntegerField(default=200)),
                ('picture', models.CharField(max_length=25, null=True)),
                ('jwt_emitted', models.IntegerField(default=0)),
            ],
        ),
    ]
