# Generated by Django 5.0.4 on 2024-04-18 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='displayName',
            field=models.CharField(max_length=25, null=True, validators=[django.core.validators.MinLengthValidator(5, 'Must contains at least 5 char')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(5, 'Must contains at least 5 char')]),
        ),
    ]
