# Generated by Django 5.0.4 on 2024-06-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_merge_0009_user_displayname_0010_user_login_42'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='displayName',
        ),
    ]
