services:
  stats-redis:
    hostname: redis
    env_file:
      - stats.env
    image: redis
    expose:
      - 6379
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  stats-postgres:
    hostname: postgres
    env_file:
      - stats.env
    image: postgres
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: stats_database_cont

  stats-service:
    depends_on:
      stats-postgres:
        condition: service_healthy
    env_file:
      - stats.env
    build:
      context: requirements/stats
      args:
        REPO: statsService
        PROJECT: statsService
        BRANCH: main
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        PORT: 5151
    expose:
      - 5151
    container_name: stats_service_cont

  stats-nginx:
    depends_on:
      stats-service:
        condition: service_healthy
    build: requirements/nginx
    ports:
      - "5151:5151"
    healthcheck:
      test: ["CMD-SHELL", "service nginx status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    container_name: stats_server_cont
